
default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mustd_development

  
test:
  <<: *default
  database: mustd_test


production:
  <<: *default
  database: mustd_production
  username: mustd
  password: <%= ENV['MUSTD_DATABASE_PASSWORD'] %>
